# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Vesto",
    "VestoCollection",
]

@typing.final
class Vesto:
    def __new__(cls) -> Vesto: ...
    def add_collection(self, name: builtins.str) -> VestoCollection:
        r"""
        Create a collection and return a handle to it.
        
        Args:
            name: collection name
        """
    def get_collection(self, name: builtins.str) -> VestoCollection:
        r"""
        Return a handle to a collection.
        
        Args:
            name: collection name
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of collections.
        """
    def __repr__(self) -> builtins.str:
        r"""
        For printing purposes.
        """

@typing.final
class VestoCollection:
    def add_index(self, vector_field: builtins.str, name: builtins.str, index_type: builtins.str, metric_name: builtins.str, dim: builtins.int) -> None:
        r"""
        Create an index in a vector field.
        
        Args:
            vector_field: name of the vector field
            name: index name
            index_type: type of index (FLAT, HSNW)
            metric_name: metric name (L2, COSINE)
            dim: dimension of the vectors
        """
    def insert(self, vector_field: builtins.str, vectors: typing.Sequence[typing.Sequence[builtins.float]], metadata: typing.Sequence[dict]) -> builtins.list[builtins.int]:
        r"""
        Insert vectors in the collection. This will update all the indexes attached.
        Return the entity_ids of the vectors inserted.
        
        Args:
            vector_field: name of the vector field
            vectors: list of vectors
            metadata: list of metadata for each vector
        """
    def search(self, vector_field: builtins.str, index_name: builtins.str, query: typing.Sequence[builtins.float], top_k: builtins.int, with_metadata: builtins.bool) -> builtins.list[tuple[builtins.float, builtins.list[builtins.float]]]:
        r"""
        Search a vector using a given index.
        
        Args:
            index_name: index name
            query: query vector
            top_k: top k matches
        """

